#!/bin/bash
#PBS -l select=1:ncpus=4:ngpus=1:mem=40gb
#PBS -l walltime=02:00:00
#PBS -N llama2_7b_lora_infer
#PBS -j oe
#PBS -o llama2_7b_lora_infer.log

module load cuda/12.1

# ===== conda =====
source /rds/general/user/yx3422/home/miniconda3/etc/profile.d/conda.sh
conda activate base 

# ===== 工作目录 =====
cd /rds/general/user/yx3422/home/m4r_project/LLaMA-Factory

# ===== GPU sanity check=====
nvidia-smi

# ===== inference =====
CUDA_VISIBLE_DEVICES=0 \
llamafactory-cli train ../Finetuning/Config/llama2_7b_lora_sft_inference.yaml

